name: AntiBlockUpdate
version: 1.0.0
main: net.gravijet.antiblockupdate.Main
author: Topsprinter
description: Disables all physical block updates in the world.
api-version: '1.13'
commands:
  portal:
    description: Manage portals.
    usage: /portal <wand|create|delete|list|info|reload>
    permission: antiblockupdate.portal
    permission-message: You don't have permission for this command.
